Repository debionetwork/debio-charts, pull requests merged in 2021-12, with the labels that each got.

#17 added debio-staking-synchronizer charts
  charts/debio-staking-synchronizer/.helmignore
  charts/debio-staking-synchronizer/Chart.yaml
  charts/debio-staking-synchronizer/templates/_helpers.tpl
  charts/debio-staking-synchronizer/templates/deployment.yaml
  charts/debio-staking-synchronizer/templates/hpa.yaml
  charts/debio-staking-synchronizer/templates/ingress.yaml
  charts/debio-staking-synchronizer/templates/secrets.yaml
  charts/debio-staking-synchronizer/templates/service.yaml
  charts/debio-staking-synchronizer/templates/serviceaccount.yaml
  charts/debio-staking-synchronizer/templates/tests/test-connection.yaml
  charts/debio-staking-synchronizer/values.yaml
Labels: add charts

#18 improve debio-customer-ui env
  charts/debio-customer-ui/Chart.yaml
  charts/debio-customer-ui/templates/_helpers.tpl
  charts/debio-customer-ui/templates/deployment.yaml
  charts/debio-customer-ui/templates/secrets.yaml
  charts/debio-customer-ui/values.yaml
Labels: enhancement

#19 improve env debio-indexer
  charts/debio-indexer/Chart.yaml
  charts/debio-indexer/templates/_helpers.tpl
  charts/debio-indexer/templates/deployment.yaml
  charts/debio-indexer/templates/secrets.yaml
  charts/debio-indexer/values.yaml
Labels: enhancement

#20 improve debio-indexer env
  charts/debio-indexer/Chart.yaml
  charts/debio-indexer/templates/_helpers.tpl
  charts/debio-indexer/templates/deployment.yaml
  charts/debio-indexer/templates/secrets.yaml
Labels: enhancement

#22 add new env debio-backend
  charts/debio-backend/templates/_helpers.tpl
  charts/debio-backend/templates/deployment.yaml
  charts/debio-backend/templates/secrets.yaml
  charts/debio-backend/values.yaml
Labels: enhancement

#23 Added ingress backed option
  charts/debio-backend/templates/ingress.yaml
  charts/debio-backend/values.yaml
Labels: feature

#24 fix secret name
  charts/debio-backend/templates/secrets.yaml
Labels: bug

#25 add new env debio-backend
  charts/debio-backend/templates/deployment.yaml
  charts/debio-backend/values.yaml
Labels: enhancement
